[package]
name = "thanos"
version = "1.0.0"
edition = "2024"

[dependencies]
chrono = "0.4.44"
libc = "0.2.186"
socket2 = { version = "0.6.3", features = ["all"] }
tokio = { version = "1.52.3", features = ["full"] }
mimalloc = "0.1.52"
num_cpus = "1.17.0"
clap = { version = "4.6.1", features = ["derive"] }
arc-swap = "1.9.1"
# Can be used to replace tokio::copy_bidirectional to increase speed by avoiding copying *large* data from kernel space to user space memory but a liability when testing with smaller responses
# tokio-splice2 = "0.3.2"

[profile.release]
lto = "fat"
codegen-units = 1
